### PR TITLE
Removing ouster_viz

### PR DESCRIPTION
**Pull request by scosar**
Removing standalone visualizer tool for Ouster

### CODE REVIEW

**Comment by marc-hanheide** [comment]
still not succeeding :-(

**Comment by scosar** [comment]
Getting a strange error: 

`fatal error: tf2_geometry_msgs/tf2_geometry_msgs.h: No such file or directory`

I checked all dependencies in CMakelist and package.xml. They all point to tf2, but still getting the error :(

**Comment by marc-hanheide** [comment]
But not to `tf2_geometry_msgs` which is a separate package?!

**Comment by marc-hanheide** [comment]
One step closer...

**Comment by scosar** [comment]
Is there a way to replicate these errors locally? Everything is fine on my local build, even from a fresh catkin workspace.

**Comment by marc-hanheide** [comment]
> Is there a way to replicate these errors locally? Everything is fine on my local build, even from a fresh catkin workspace.

That's because you have installed loads of thing locally already. Or you are not building in isolation?

best idea is to run (assuming you are in the top dir of your workspace):
```
rosdep update
rosdep install -i --from-paths src/
catkin_make_isolated --install
```

Did you try this?

**Comment by marc-hanheide** [comment]
Hooray!

**Comment by scosar** [comment]
Cool! :) Shall we merge it?

**Pull request merged**
